Resources:
  CloudTrailLogging:
    Type: AWS::CloudTrail::Trail
    Properties:
      IsLogging: true
      S3BucketName:
        Ref: LoggingBucket
      TrailName: cf-fuguetest-trail
      EventSelectors:
        - ReadWriteType: All
          DataResources:
            - Type: AWS::S3::Object
              Values:
                - Fn::Sub: "${LoggingBucket1.Arn}/"
                - Fn::Sub:
                    - "${Bucket}/"
                    - Bucket: LoggingBucket2
  LoggingBucket1:
    Type: AWS::S3::Bucket
  LoggingBucket2:
    Type: AWS::S3::Bucket
