Resources:
  CloudTrailLogging:
    Type: AWS::CloudTrail::Trail
    Properties:
      IsLogging: true
      S3BucketName:
        Ref: LoggingBucket
      TrailName: cf-fuguetest-trail
      EventSelectors:
      - ReadWriteType: All
        DataResources:
        - Type: AWS::S3::Object
          Values:
            - Fn::Join:
              - ''
              - - Fn::Join:
                  - 'arn:aws:s3:::'
                  - - Fn::Join:
                      - '-'
                      - - Ref: AWS::Region
                        - Ref: AWS::AccountId
