/*
 * Policy Engine I/O Formats
 *
 * Documentation for the input and output formats used in Policy Engine
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Information about a rule bundle that was used in the evaluation
type RuleBundleInfo struct {
	RuleBundle *RuleBundle `json:"rule_bundle,omitempty"`
	// Any errors that occurred while initializing this rule bundle
	Errors []string `json:"errors,omitempty"`
}
