/*
 * Policy Engine I/O Formats
 *
 * Documentation for the input and output formats used in Policy Engine
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// The state format contains the state of all resources from some input. This format is intended to be used as both an input and output for the policy engine.
type State struct {
	Format        string `json:"format"`
	FormatVersion string `json:"format_version"`
	// The type of input that this state was generated from. This value factors into which rules are run for this input.
	InputType string `json:"input_type"`
	// The type of environment that this state was generated from. This value factors into which rules are run for this input.
	EnvironmentProvider string `json:"environment_provider"`
	// This object is intended to hold any input type-specific or environment-specific fields, e.g. account_id or filepath.
	Meta map[string]interface{} `json:"meta,omitempty"`
	// Resources is a map of resource type to a map of a unique resource key to a resource object.
	Resources map[string]map[string]ResourceState `json:"resources"`
	// Describes the origin of the input, e.g. filepath + branch for IaC files, or account/region for cloud resources
	Scope map[string]interface{} `json:"scope,omitempty"`
}
