/*
 * Policy Engine I/O Formats
 *
 * Documentation for the input and output formats used in Policy Engine
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// A rule set that was used in the evaluation
type RuleSet struct {
	Name     string `json:"name,omitempty"`
	Source   string `json:"source,omitempty"`
	Checksum string `json:"checksum,omitempty"`
}
