/*
 * Policy Engine I/O Formats
 *
 * Documentation for the input and output formats used in Policy Engine
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// A graph edge that describes a relationship between two resources
type Edge struct {
	Label  string `json:"label"`
	Source *Node  `json:"source"`
	Target *Node  `json:"target"`
}
