AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        exports.handler = (event, context) => {
          console.log(JSON.stringify(event))
        }
      Handler: index.handler
      Runtime: nodejs12.x
  FunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Function.Arn
      Action: lambda:InvokeFunction
      Principal: "*"
