name: rc

on:
  push:
    branches:
      - 'release/**'

jobs:
  rc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: make install_tools
      - name: Extract version name from git branch
        id: version
        run: echo "VERSION=v${GITHUB_REF#*release/}" >> $GITHUB_OUTPUT
      - name: Ensure changelog exists
        run: ls changes/${{ steps.version.outputs.VERSION }}.md
      - name: Generate extra files
        run: make release_extra_files
      - name: Run goreleaser
        run: goreleaser build --snapshot
