name: release

on:
  push:
    tags:
    - "v*"

jobs:
  release:
    environment: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - run: make install_tools
    - name: Extract tag name from git ref
      id: tag_name
      run: echo "TAG_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
    - name: Ensure changelog exists
      run: ls changes/${{ steps.tag_name.outputs.TAG_NAME }}.md
    - name: Run goreleaser
      run: |
        goreleaser release \
          --release-notes=changes/${{ steps.tag_name.outputs.TAG_NAME }}.md \
          --skip-validate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
